export enum ChainEventType {
  CREATE_ORG_CONTRACT = 'CREATE_ORG_CONTRACT',
  DEPOSIT_FUNDS = 'DEPOSIT_FUNDS',
  WITHDRAW_FUNDS = 'WITHDRAW_FUNDS',
  CREATE_ASSET = 'CREATE_ASSET',
  TRANSFER_ASSET = 'TRANSFER_ASSET',
  VERIFY_ASSET = 'VERIFY_ASSET',
  LICENSE_ASSET = 'LICENSE_ASSET',
  GRANT_CREATOR_ROLE = 'GRANT_CREATOR_ROLE',
  REVOKE_CREATOR_ROLE = 'REVOKE_CREATOR_ROLE',
  FUND_USER_WALLET = 'FUND_USER_WALLET',
  WITHDRAW_ORG_EARNINGS = 'WITHDRAW_ORG_EARNINGS',
}
